spring.application.name=biblioteca-pessoal

# MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=biblioteca_pessoal

# Thymeleaf
spring.thymeleaf.cache=false

# Logging
logging.level.com.example.biblioteca=DEBUG
